# NOTE: This file is not designed to be run independently.
#
# Instead, use it with a file for a specific OS and Swift version, for example:
#
# % docker-compose \
#   -f docker/docker-compose.yaml \
#   -f docker/docker-compose.2204.58.yaml \
#   run test
#
version: "3"

services:
  runtime-setup:
    image: &image swift-openapi-urlsession:default
    build:
      context: .
      dockerfile: Dockerfile
    # Note: This temporary step creates a gitconfig to use SSH for a dependency
    # that is not yet public. This can be removed once it is public.
    command: git config --global url."git@github.com:apple/swift-openapi-runtime".insteadOf "https://github.com/apple/swift-openapi-runtime"
    volumes:
      - ci-gitconfig:/ci-gitconfig
    environment:
      - GIT_CONFIG_GLOBAL=/ci-gitconfig/gitconfig

  common: &common
    image: *image
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code:z
      - ci-gitconfig:/ci-gitconfig
    working_dir: /code
    environment:
      - GIT_CONFIG_GLOBAL=/ci-gitconfig/gitconfig

  soundness:
    <<: *common
    command: /bin/bash -xcl "swift -version && uname -a && ./scripts/soundness.sh"

  test:
    <<: *common
    command: /bin/bash -xcl "swift $${SWIFT_TEST_VERB-test} $${WARN_AS_ERROR_ARG-} $${SANITIZER_ARG-} $${IMPORT_CHECK_ARG-}"

  shell:
    <<: *common
    entrypoint: /bin/bash

volumes:
  ci-gitconfig:
